// component MenuButton inherits Rectangle {
//     width: 100px;
//     height: 100px;

//     in property <length> image-size: 100px;
//     in property <image> image-path: @image-url("");

//     in property <brush> bg-color: #cccccc;
//     in property <brush> bg-hover-color: #ffffff;
//     in property <brush> text-color: #000000;

//     background: bg-color;
//     border-radius: 0px;

//     animate background {
//         duration: 150ms;
//         easing: ease-out;
//     }

//     Image {
//         source: image_path;
//         width: image_size;
//         x: 30px;
//     }

//     // Button knob
//     knob := Rectangle {

//     }

//     callback clicked();

//     ta := TouchArea {
//         clicked => {
//             clicked();
//             active = !active;
//         }
//     }

//     property <bool> active: false;
//     states [
//         active when ta.pressed: {
//             root.background: bg-hover-color;
//         }
//     ]  
// }
import { OldButton } from "../components/old.slint";


component HomeMenu inherits HorizontalLayout { 

    callback modusoft-kne();
    callback modusoft-ots();
    callback modusoft-thy();
    callback modusoft-ora();
    callback modusoft-sch();

    spacing: 7px;
    x: root.width / 2 - self.width / 5;
    y: root.height / 2 - self.height / 4;
    VerticalLayout {
        spacing: 7px;
        OldButton {
            text: "Modu-soft.kne";
            clicked => {
                modusoft-kne();
            }
        }
        OldButton {
            text: "Modu-soft.ots";
            clicked => {
                modusoft-ots();
            }
        }
        OldButton {
            text: "Modu-soft.thy";
            clicked => {
                modusoft-thy();
            }
        }
    }
    VerticalLayout {
        spacing: 7px;

        OldButton {
            text: "Modu-soft.ora";
            clicked => {
                modusoft-ora();
            }
        }
        OldButton {
            text: "Modu-soft.sch";
            clicked => {
                modusoft-sch();
            }
        }
    }
}

export component MenuPage inherits Rectangle {
    width: 1280px;
    height: 800px;
    background: #ffffff;

    callback to-schindler-page();
    callback to-schindler-double-page();
    callback to-otis-page();

    // TEST //
    callback to-modusoft-kne();
    callback to-modusoft-ots();
    callback to-modusoft-thy();
    callback to-modusoft-ora();
    callback to-modusoft-sch();
    // TEST //
    
    // Rectangle {
    //     background: @linear-gradient(180deg, #d1e6f5 10%,  #6bbfe9 100%);
    //     border-radius: 5px;
    //     width: 60%;
    //     height: 70%;


    //     VerticalLayout {
    //         padding: 20px;
    //         spacing: 40px;

    //         Image {
    //             source: @image-url("../images/logo_modusystem.png");
    //             padding: 20px;
    //             height: 100px;
    //             image-fit: contain;
    //         }

    //         VerticalLayout {
    //             spacing: 20px;

    //             MenuButton {
    //                 image_path: @image-url("../images/1024px-Otis_logo.png");
    //                 bg-color: @linear-gradient(135deg, #ffffff 10%,  #67a4ff 100%);
    //                 bg-hover-color: @linear-gradient(135deg, #ffffff 10%,  #2c80fd 100%);
    //                 border-radius: 3px;
    //                 x: 50px;
    //                 width: 630px;

    //                 clicked => { to-otis-page() }
    //             }
                
    //             MenuButton {
    //                 x: 50px;
    //                 image_path: @image-url("../images/Logo-schindler.png");
    //                 border-radius: 3px;
    //                 bg-color: @linear-gradient(135deg, #ffffff 10%,  #ff676f 100%);
    //                 bg-hover-color: @linear-gradient(135deg, #ffffff 10%,  #ff3842 100%);
    //                 width: 630px;

    //                 clicked => { to-schindler-page() }
    //             }

    //             MenuButton {
    //                 x: 50px;
    //                 image_path: @image-url("../images/Logo-schindler.png");
    //                 border-radius: 3px;
    //                 bg-color: @linear-gradient(135deg, #ffffff 10%,  #ff676f 100%);
    //                 bg-hover-color: @linear-gradient(135deg, #ffffff 10%,  #ff3842 100%);
    //                 width: 630px;

    //                 clicked => { to-schindler-double-page() }
    //             }
    //         }  
    //     }
    // }
    
    HomeMenu { 
            modusoft-kne => {to-modusoft-kne()}
            modusoft-ots => {to-modusoft-ots()} 
            modusoft-thy => {to-modusoft-thy()} 
            modusoft-ora => {to-modusoft-ora()} 
            modusoft-sch => {to-modusoft-sch()} 
        }

    VerticalLayout {
        padding: 40px;
        VerticalLayout {
            width: 240px;
            OldButton {
                width: 240px;
                height: 56px;
    
                text: "Support";
                font-size: 37px;
                font-weight: 400;
            }
            Text {
                horizontal-alignment: right; 
                text: "Verison 10.58_15";
                font-size: 25px;
                font-weight: 400;
                color: #b5b5b5;
            }
        }
    }
}