import { Button, Radio, ProgressBar } from "../components/new.slint";

component InspectSwitch inherits Rectangle {
    width: 196px;
    height: 180px;
    Text {
        text: "NORMAL";
        y: 0;
        x: root.width/2 - self.width/2 - 18px;
        font-weight: 500;

    }

    Text {
        text: "INSP.";
        y: 91px;
        x: root.width/2 - self.width/2 + 80px;
        font-weight: 500;

    }

    Button {
        y: 20px;
        x: root.width/2 - self.width/2 - 18px;
        width: 160px;
        height: self.width;
        bg-color: transparent;

        icon: @image-url("../images/Inspection_black.png");
        icon-height: self.height; 
        icon-width: self.width;
        icon-rotation-angle: 90deg;

        animate icon-rotation-angle {
            duration: 0.4s;
            easing: ease-out-expo;
        }

        clicked => {
            if self.icon-rotation-angle == 0deg{
                self.icon-rotation-angle = 90deg;
            }
            else{
                self.icon-rotation-angle = 0deg;
            }
        }
    }
}

component InspectButton inherits Rectangle {
    width: 100px;
    height: 120px;

    in property <image> icon: @image-url("../images/DRESG-E.png");
    in property <string> text: "DRESG-E";

    Button {
        width: 100px;
        height: 100px;
        y: 0px;
        
        bg-color: transparent;

        icon: icon;
        icon-height: 100px; 
        icon-width: 100px; 
    }

    Text {
        text: text;
        y: 104px;
        font-weight: 500;
        color: #b6b6b6;
    }
}

component FloorLevelSlider inherits Rectangle {
    in property <int> floor-count: 5;

    in property <brush> empty-color;
    in property <brush> filled-color: @linear-gradient(0deg, #003cc8 0, #81c8ff 100);

    in property <length> length: 400px;
    in property <length> thickness: 4px;

    in property <int> progress : 75;


    in property <length> floor-size: 17px;

    width: 50px;
    height: length + 20px;

    bar := ProgressBar {
        progress-bar-inner-radius: 0;
        progress-bar-outer-radius: 0;

        progress: root.progress;

        orientation: Vertical;

        
        length: root.length;
        thickness: root.thickness;

        bg-color: #444444;
        bar-color: filled-color;
    }

    for value[i] in floor-count: Rectangle {
        width: floor-size;
        height: floor-size;
        border-radius: self.width / 2;

        y: (floor-count - 1 - i) * (root.length / (floor-count - 1));
    
        background: {
            if bar.progress > (100 / (floor-count - 1)) * i {   
                #269bf4;
            }
            else {
                #444444;
            }
        }

        Rectangle {
            width: parent.width / 1.75;
            height: parent.height / 1.75;
            border-radius: self.width / 2;
            background: #2b2b2b;
        }
    }
}

component Led inherits Rectangle {
    width: 15px;
    height: 13px;

    background: #ffffff;
    Rectangle {
        x: 0;
        y: 0;
        background: @linear-gradient(-45deg, #ffffff 49%, #a0a0a0 50%);
        width: 5px;
        height: 5px;
    }
    Rectangle {
        width: parent.height - 2px;
        height: parent.height - 2px;
        border-radius: self.width / 2;
        background: #dddddd;
    }
}

export component SchindlerTestPage inherits Rectangle {
    width: 1280px;
    height: 800px;

    // callback back-to-menu-page();
    in-out property <string> console-output;

    background: #2B2B2B;
    
    GridLayout {
        padding: 20px;

        // TOP
        Row {
            GridLayout {
                height: root.height * 0.45;
                
                Rectangle {
                    col: 0;
                    height: parent.height;
                    width: 350px;
        
                    property <length> x-offset: 0px;
                    property <length> y-offset: -20px;
        
                    // NOR/INSP. Switch
                    InspectSwitch {
                        x: parent.width/2 - self.width/2 + 50px + x-offset;
                        y: 60px + y-offset;
                    }
                    
                    // DRESG-E Button
                    InspectButton {
                        x: 110px + x-offset;
                        y: 240px + y-offset;
                    }
                    
                    // DRESG-D Button
                    InspectButton {
                        x: 225px + x-offset;
                        y: 232px + y-offset;
                        icon: @image-url("../images/DRESG-D.png");
                        text: "DRESG-D";
                    }
        
                    // DRESG-U Button
                    InspectButton {
                        x: 22px + x-offset;
                        y: 160px + y-offset;
                        icon: @image-url("../images/DRESG-U.png");
                        text: "DRESG-U";
                    }
        
                    // Stop Button
                    Button {
                        icon: @image-url("../images/Stop.png");
        
                        width: 130px;
                        height: 130px;
                        border-radius: self.width / 2;
        
                        x: 8px + x-offset;
                        y: 17px + y-offset;
                        
                        bg-color: transparent;
                        bg-select-color: transparent;
                        drop-shadow-color: #00000085;
                        drop-shadow-offset-x: 6px;
                        drop-shadow-offset-y: 5px;
                        drop-shadow-blur: 5px;

                        icon-width: self.width;
                        icon-height: self.height;

                        animate icon-width, icon-height {
                             duration: 0.3s;
                             easing: ease-out;
                        }

                        property <bool> toggled;
                        clicked => {
                            toggled = !toggled;

                            self.icon-width = toggled ? 126px : 130px;
                            self.icon-height = toggled ? 126px : 130px;
                        }

                        
                    }
                }

                VerticalLayout {
                    col: 1;
                    height: parent.height;
                    Rectangle {
                        FloorLevelSlider {
                            Image {
                                source: @image-url("../images/ElevatorPos.png");
                                width: 40px;
                                height: 40px;
                                y: parent.length - parent.length * parent.progress / 100 - self.height / 2;
                            }   
                            length: 270px;
                            progress: 50;
                            floor-count: 4;
                            floor-size: 12px;
                            x: 30px;
                        }
                    }
                }

                Rectangle {
                    col: 2;
                    width: 255px;
                    VerticalLayout {
                        alignment: start;

                        HorizontalLayout {
                            spacing: 2px;
                            alignment: center;
    
                            Rectangle {
                                background: #8ea5b1;
                                width: 80px;
                                height: 120px;
                                border-radius: 1.5px;
                                
                                Text {
                                    text: "0";
                                    font-family: "DS-Digital";
                                    font-size: 120px;
                                    vertical-alignment: top;
                                    horizontal-alignment: center;
                                }
        
                                Rectangle {
                                    width: 8px;
                                    height: 8px;
                                    border-radius: self.width / 2;
                                    background: #ffffff;
                                    x: 4px;
                                    y: parent.height - self.height - 16px;
                                }
        
                                Rectangle {
                                    width: 8px;
                                    height: 8px;
                                    border-radius: self.width / 2;
                                    background: #ffffff;
                                    x: parent.width - self.width - 4px;
                                    y: parent.height - self.height - 16px;
                                }
                            }
        
                            Rectangle {
                                background: #8ea5b1;
                                width: 80px;
                                height: 120px;
                                border-radius: 1.5px;
                                
                                Text {
                                    text: "0";
                                    font-family: "DS-Digital";
                                    font-size: 120px;
                                    vertical-alignment: top;
                                    horizontal-alignment: center;
                                }
        
                                Rectangle {
                                    width: 8px;
                                    height: 8px;
                                    border-radius: self.width / 2;
                                    background: #ffffff;
                                    x: 4px;
                                    y: parent.height - self.height - 16px;
                                }
        
                                Rectangle {
                                    width: 8px;
                                    height: 8px;
                                    border-radius: self.width / 2;
                                    background: #ffffff;
                                    x: parent.width - self.width - 4px;
                                    y: parent.height - self.height - 16px;
                                }
                            }
                        }

                        HorizontalLayout {
                            alignment: center;
                            
                            VerticalLayout {
                                alignment: center;
                                padding: 10px;
                                height: 100px;
                                spacing: 20px;
                                GridLayout {
                                    spacing-horizontal: 16px;
                                    spacing-vertical: 0px;
    
                                    Row {
                                        Led {col: 1;}
                                    }
    
                                    Row {
                                        Led {}
                                        Led {col: 2;}
                                    }
                                }

                                GridLayout {
                                    spacing-horizontal: 16px;
                                    spacing-vertical: 0px;
    
                                    Row {
                                        Led {}
                                        Led {col: 2;}
                                    }
                                    
                                    Row {
                                        Led {col: 1;}
                                    }
                                }
                            }
                        }

                        HorizontalLayout {
                            spacing: 2px;
                            alignment: center;
    
                            Rectangle {
                                background: #8ea5b1;
                                width: 80px;
                                height: 120px;
                                border-radius: 1.5px;
                                
                                Text {
                                    text: "0";
                                    font-family: "DS-Digital";
                                    font-size: 120px;
                                    vertical-alignment: top;
                                    horizontal-alignment: center;
                                }
        
                                Rectangle {
                                    width: 8px;
                                    height: 8px;
                                    border-radius: self.width / 2;
                                    background: #ffffff;
                                    x: 4px;
                                    y: parent.height - self.height - 16px;
                                }
        
                                Rectangle {
                                    width: 8px;
                                    height: 8px;
                                    border-radius: self.width / 2;
                                    background: #ffffff;
                                    x: parent.width - self.width - 4px;
                                    y: parent.height - self.height - 16px;
                                }
                            }
        
                            Rectangle {
                                background: #8ea5b1;
                                width: 80px;
                                height: 120px;
                                border-radius: 1.5px;
                                
                                Text {
                                    text: "0";
                                    font-family: "DS-Digital";
                                    font-size: 120px;
                                    vertical-alignment: top;
                                    horizontal-alignment: center;
                                }
        
                                Rectangle {
                                    width: 8px;
                                    height: 8px;
                                    border-radius: self.width / 2;
                                    background: #ffffff;
                                    x: 4px;
                                    y: parent.height - self.height - 16px;
                                }
        
                                Rectangle {
                                    width: 8px;
                                    height: 8px;
                                    border-radius: self.width / 2;
                                    background: #ffffff;
                                    x: parent.width - self.width - 4px;
                                    y: parent.height - self.height - 16px;
                                }
                            }
                        }
                    }
                }
            }
        }
        
        //BOTTOM
        Row {
            GridLayout {
                spacing-horizontal: 15px;
                height: root.height * 0.45;

                property <int> current-page: 0;

                
                // MODES ???
                // Rectangle {
                //     width: 170px;
                //     clip: true;
                //     background: transparent;
                //     border-color: #646363;
                //     border-width: 1px;


                //     sgr := SwipeGestureHandler {
                //         handle-swipe-right: current-page > 0;
                //         handle-swipe-left: current-page < 1;
                //         swiped => {
                //             if self.current-position.x > self.pressed-position.x + self.width / 4 {
                //                 current-page -= 1;
                //             } else if self.current-position.x < self.pressed-position.x - self.width / 4 {
                //                 current-page += 1;
                //             }
                //         }
                
                //         HorizontalLayout {
                //             property <length> position: - current-page * 170px;
                //             animate position { duration: 200ms; easing: ease-in-out; }
                //             property <length> swipe-offset;
                //             x: position + swipe-offset;
                //             states [
                //                 swiping when sgr.swiping : {
                //                     swipe-offset: sgr.current-position.x - sgr.pressed-position.x;
                //                     out { animate swipe-offset { duration: 200ms; easing: ease-in-out; }  }
                //                 }
                //             ]
                            
                //             HorizontalLayout {
                //                 width: 170px;
                //                 Rectangle {
                //                     VerticalLayout {
                //                         padding: 5px;
                //                         spacing: 20px;
                //                         Text {
                //                             height: 42px;
                //                             font-size: 22px;
                //                             font-weight: 500;
                //                             vertical-alignment: bottom;
                //                             horizontal-alignment: center;
                //                             text: "Listmode";
                //                             Rectangle {
                //                                 background: #ffffff;
                //                                 width: 90px;
                //                                 y: parent.height - self.height;
                //                                 height: 2px;
                //                             }
                //                         }
                
                //                         Rectangle {
                //                             Flickable {
                //                                 interactive: true;
                //                                 width: 150px;
                //                                 VerticalLayout {
                //                                     spacing: 10px;
                                                    
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                 }
                //                             }
                //                         }
                //                     }
                //                 }
                //             }
    
                //             HorizontalLayout {
                //                 width: 170px;
                //                 Rectangle {
                //                     VerticalLayout {
                //                         padding: 5px;
                //                         spacing: 20px;
                //                         Text {
                //                             height: 42px;
                //                             font-size: 22px;
                //                             font-weight: 500;
                //                             vertical-alignment: bottom;
                //                             horizontal-alignment: center;
                //                             text: "Command";
                //                             Rectangle {
                //                                 background: #ffffff;
                //                                 width: 120px;
                //                                 y: parent.height - self.height;
                //                                 height: 2px;
                //                             }
                //                         }
                
                //                         Rectangle {
                //                             Flickable {
                //                                 interactive: true;
                //                                 width: 150px;
                //                                 VerticalLayout {
                //                                     spacing: 10px;
                                                    
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;
                                
                //                                     }
                //                                     Button {
                //                                         // width: parent.width - 18px;
                //                                         x: parent.width / 2 - self.width / 2;
                //                                         height: 52px;
                                
                //                                         bg-color: #0c0c0c;
                //                                         text: "Common";
                //                                         font-weight: 400;

                //                                     }
                //                                 }
                //                             }
                //                         }
                //                     }
                //                 }
                //             }
                //         }
                //     }
                // }
                
                // CONSOLE
                Rectangle {
                    background: #423F3E;
                    border-width: 1px;
                    border-color: #646363;
                    
                    HorizontalLayout {
                        padding: 5px;
                        padding-left: 10px;
                        padding-right: 10px;

                        Text {
                            text: console-output;
                            font-size: 14px;
                            vertical-alignment: bottom;
                            horizontal-alignment: left;
                        }
                    }
                }

                // KEYPAD
                // GridLayout {
                //         col: 2;
                //         spacing-vertical: 0px;
                //         spacing-horizontal: 45px;

                //         property <length> keypad-width: 52px;
                //         property <length> keypad-height: 52px;
                //         property <length> keypad-radius: 12px;
                //         property <brush> keypad-background: #5c5c5c;
                //         property <length> keypad-font-size: 22px;
                //         property <brush> keypad-font-color: #ffffff;
                //         property <int> keypad-font-weight: 400;

                //         property <brush> keypad-label-color: #FFD336;
                //         property <length> keypad-label-font-size: 20px;
                //         property <length> keypad-label-offset: -3px;
                //         property <length> keypad-label-width: 1px;
                //         property <length> keypad-label-padding: 3px;

                //         Row {
                //             // 1  
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "1";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
    
                //             // 2
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "2";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
    
                //             // 3
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "3";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
                //         }

                //         Row {
                //             // 4
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "4";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
    
                //             // 5
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "5";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
    
                //             // 6
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "6";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
                //         }

                //         Row {
                //             // 7
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "7";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
    
                //             // 8
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "8";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
    
                //             // 9
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "9";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
                //         }

                //         Row {
                //             // -
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "―";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
                            
                //             // 0
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "0";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
    
                //             // *
                //             VerticalLayout {
                //                 spacing: keypad-label-offset;
                //                 Text {
                //                     text: "✱";
                //                     vertical-alignment: bottom;
                //                     horizontal-alignment: center;
                //                     font-size: keypad-label-font-size;
                //                     stroke: keypad-label-color;
                //                     stroke-style: outside;
                //                     color: #2b2b2b;
                //                 }
                //                 Rectangle {
                //                     width: keypad-width + keypad-label-padding;
                //                     height: keypad-height + keypad-label-padding;
                //                     border-width: keypad-label-width;
                //                     border-color: keypad-label-color;
                //                     Button {
                //                         width: keypad-width;
                //                         height: keypad-height;
                //                         bg-color: keypad-background;
            
                //                         border-radius: keypad-radius;
            
                //                         icon: @image-url("../images/MechanicalButton.png");
                //                         icon-width: keypad-width;
                //                         icon-height: keypad-height;
            
                //                         font-size: keypad-font-size;
                //                         text-color: keypad-font-color;
                //                         font-weight: keypad-font-weight;
                //                     }
                //                 }
                //             }
                //         }

                //         Row {
                //         // Door Close
                //         VerticalLayout {
                //             spacing: keypad-label-offset;
                //             Text {
                //                 text: "><";
                //                 vertical-alignment: bottom;
                //                 horizontal-alignment: center;
                //                 font-size: keypad-label-font-size;
                //                 stroke: keypad-label-color;
                //                 stroke-style: outside;
                //                 color: #2b2b2b;
                //             }
                //             Rectangle {
                //                 width: keypad-width + keypad-label-padding;
                //                 height: keypad-height + keypad-label-padding;
                //                 border-width: keypad-label-width;
                //                 border-color: keypad-label-color;
                //                 Button {
                //                     width: keypad-width;
                //                     height: keypad-height;
                //                     bg-color: keypad-background;
        
                //                     border-radius: keypad-radius;
        
                //                     icon: @image-url("../images/MechanicalButton.png");
                //                     icon-width: keypad-width;
                //                     icon-height: keypad-height;
        
                //                     font-size: keypad-font-size;
                //                     text-color: keypad-font-color;
                //                     font-weight: keypad-font-weight;
                //                 }
                //             }
                //         }

    
                //         // Door Open
                //         VerticalLayout {
                //             spacing: keypad-label-offset;
                //             col: 2;
                //             Text {
                //                 text: "<>";
                //                 vertical-alignment: bottom;
                //                 horizontal-alignment: center;
                //                 font-size: keypad-label-font-size;
                //                 stroke: keypad-label-color;
                //                 stroke-style: outside;
                //                 color: #2b2b2b;
                //             }
                //             Rectangle {
                //                 width: keypad-width + keypad-label-padding;
                //                 height: keypad-height + keypad-label-padding;
                //                 border-width: keypad-label-width;
                //                 border-color: keypad-label-color;
                //                 Button {
                //                     width: keypad-width;
                //                     height: keypad-height;
                //                     bg-color: keypad-background;
        
                //                     border-radius: keypad-radius;
        
                //                     icon: @image-url("../images/MechanicalButton.png");
                //                     icon-width: keypad-width;
                //                     icon-height: keypad-height;
        
                //                     font-size: keypad-font-size;
                //                     text-color: keypad-font-color;
                //                     font-weight: keypad-font-weight;
                //                 }
                //             }
                //         }
                //     }
                // }
            }
        }
    }
}