import { Pallet, OnlineNetworkIcon } from "./style.slint";
import { SimpleButton } from "buttons.slint";

export global HeaderLogic {
    in-out property <bool> maximized: false;
    
    callback to-home-page();
    callback to-settings-page();
}

component HeaderItem inherits SimpleButton {
    in-out property <int> id;

    in property <image> icon;
    in property <length> icon-width: 30px;
    in property <length> icon-height: 30px;
    in property <brush> colorize: transparent;

    in property <string> title : "Title";

    callback on-clicked();
    
    in property <length> parent-width: 50px;
    
    width: HeaderLogic.maximized ? parent-width - 24px : parent-width;
    height: 50px;

    background: transparent;
    background-select: #222222;
    
    Image {
        source: icon;
        width: icon-width;
        height: icon-height;
        x: parent.height / 2 - self.width / 2;
        colorize: root.colorize;
    }

    if HeaderLogic.maximized: Text {
        text: title;
        font-family: "Roboto";
        x: 60px;
        y: 4px;
        color: transparent;
        font-size: 18px;
        font-weight: 200;
        horizontal-alignment: center;
        vertical-alignment: center;

        init => {
            self.y = self.height/2;
            self.color = Pallet.header-text;
        }

        animate y, color {
            delay: 0.25s + (0.1s * id);
            duration: 0.5s;
            easing: ease-out;
        }
    }

    clicked => {
        on-clicked();
    }
}

export component Header {
    height: 800px;
    width: 50px;
    x: 0px;

    animate width {
         duration: 0.5s;
         easing: ease-out-expo;
    }

    in property <int> connection-strength: 4;
    in property <string> title;

    Rectangle {
        background: Pallet.header-background;

        // To prevent clicking buttons behind the navigation bar
        TouchArea { width: parent.width; height: parent.height; }

        // When the navigation bar is expanded, if the user clicks outside of it, it will collapse again
        if HeaderLogic.maximized : TouchArea { 
            x: parent.width; 
            height: parent.height; 
            width: 1280px - 50px;

            clicked => {
                HeaderLogic.maximized = !HeaderLogic.maximized;

                if (HeaderLogic.maximized) {
                    root.width = 225px;

                    title-pane.padding = 15px;
                    title-pane.padding-top = 8px;
                    
                    title-pane-icon.width = 50px;
                    title-pane-icon.height = 50px;

                    title-pane-spacer.y = 10px;

                    navigation-bar-icons.padding = 12px;
                    navigation-bar-icons.padding-top = 15px;

                    collapse-button.padding = 15px;
                    collapse-button.padding-top = 0px;
                    collapse-button.padding-bottom = 0px;
                } else {
                    root.width = 50px;

                    title-pane.padding = 5px;
                    title-pane.padding-top = 5px;

                    title-pane-icon.width = 40px;
                    title-pane-icon.height = 40px;

                    title-pane-spacer.y = 0px;

                    navigation-bar-icons.padding = 0px;
                    navigation-bar-icons.padding-top = 15px;

                    collapse-button.padding = 0px;
                }
            }
        }

        VerticalLayout {
            spacing: 4px;
            
            title-pane := HorizontalLayout {
                width: 50px;
                height: 50px;
                padding: 5px;
                padding-top: 5px;

                animate padding, padding-top {
                    duration: 0.5s;
                    easing: ease-out-expo;  
                }

                title-pane-icon := Image {
                    source: @image-url("../assets/icons/Logo.png");
                    width: 40px;
                    height: 40px;       
                    
                    animate width, height {
                        duration: 0.5s;
                        easing: ease-out-expo;  
                    }
                }

                Rectangle {
                    width: 130px;
                    if HeaderLogic.maximized: Text {
                        text: title;
                        font-family: "Roboto";
                        width: 100px;
                        color: transparent;
                        y: -7px;
                        font-size: 18px;
                        font-weight: 600;
                        wrap: word-wrap;
                        horizontal-alignment: left;
                        vertical-alignment: center;
    
                        init => {
                            self.y = 3px;
                            self.color = #ffffff;
                        }
    
                        animate y, color {
                            delay: 0.25s;
                            duration: 0.5s;
                            easing: ease-out;
                        }
                    }
                }
            }
            
            // SPACER
            Rectangle {
                height: 20px;
                title-pane-spacer := Rectangle {
                    width: root.width - 8px;
                    height: 1px;
                    x: 4px;
                    y: 0px;
                    background: Pallet.header-icon-primary;

                    animate y {
                         duration: 0.5s;
                         easing: ease-out-expo;
                    }
                }
            }
            
            navigation-bar-icons := VerticalLayout {
                spacing: 20px;
                padding: 0px;
                padding-top: 15px;

                animate padding {
                     duration: 0.5s;
                     easing: ease-out-expo;
                }

                // Home
                HeaderItem {
                    id: 0;
                    icon: @image-url("../assets/icons/Home.png");
                    colorize: Pallet.header-icon-primary;
                    parent-width: parent.width;
                    title: "Home";
                    on-clicked => {
                        HeaderLogic.to-home-page();
                    }
                }

                HeaderItem {
                    id: 1;
                    parent-width: parent.width;
                    title: "Local network";
                    height: 50px;
                    icon: @image-url("../assets/icons/OnlineNetworkIcon_NoConnection.png");
                }

                HeaderItem {
                    id: 1;
                    parent-width: parent.width;
                    title: "Online network";
                    height: 50px;
                    icon: @image-url("../assets/icons/LocalNetworkIcon_NoConnection.png");
                    icon-width: 35px;
                    icon-height: 35px;
                }

                HeaderItem {
                    id: 2;
                    parent-width: parent.width;
                    title: "Bluetooth";
                    height: 50px;
                    icon: @image-url("../assets/icons/Bluetooth.png");
                    icon-width: 40px;
                    icon-height: 40px;
                    colorize: Pallet.header-icon-primary;
                }

                HeaderItem {
                    id: 2;
                    parent-width: parent.width;
                    title: "Settings";
                    height: 50px;
                    icon: @image-url("../assets/icons/Settings.png");
                    icon-width: 35px;
                    icon-height: 35px;
                    colorize: Pallet.header-icon-primary;

                    clicked => {
                        HeaderLogic.to-settings-page();
                    }
                }

                HeaderItem {
                    id: 3;
                    parent-width: parent.width;
                    title: "Language";
                    height: 50px;
                    icon: @image-url("../assets/icons/Language.png");
                    icon-width: 32px;
                    icon-height: 32px;
                    colorize: Pallet.header-icon-primary;
                }
            }

            
            
            VerticalLayout {
                alignment: end;
                padding-bottom: 16px;
                spacing: 12px;

                // SPACER
                Rectangle {
                    width: root.width - 8px;
                    height: 1px;
                    x: 4px;
                    background: Pallet.header-icon-primary;
                }

                collapse-button := HorizontalLayout {
                    padding: 0px;
                    padding-top: 0px;
                    padding-bottom: 0px;

                    animate padding, padding-top, padding-bottom {
                        duration: 0.5s;
                        easing: ease-out-expo;    
                    }
                    HeaderItem {
                        id: 4;
                        icon: @image-url("../assets/icons/SideBar_Minimize.png");
                        title: "Collapse";
                        parent-width: parent.width;
                        on-clicked => {
                            HeaderLogic.maximized = !HeaderLogic.maximized;
                            debug(HeaderLogic.maximized);
    
                            if (HeaderLogic.maximized) {
                                root.width = 225px;
    
                                title-pane.padding = 15px;
                                title-pane.padding-top = 8px;
                                
                                title-pane-icon.width = 50px;
                                title-pane-icon.height = 50px;
    
                                title-pane-spacer.y = 10px;
    
    
                                navigation-bar-icons.padding = 12px;
                                navigation-bar-icons.padding-top = 15px;

                                collapse-button.padding = 15px;
                                collapse-button.padding-top = 0px;
                                collapse-button.padding-bottom = 0px;
    
    
                            } else {
                                root.width = 50px;
    
                                title-pane.padding = 5px;
                                title-pane.padding-top = 5px;
    
                                title-pane-icon.width = 40px;
                                title-pane-icon.height = 40px;
    
                                title-pane-spacer.y = 0px;
    
                                navigation-bar-icons.padding = 0px;
                                navigation-bar-icons.padding-top = 15px;

                                collapse-button.padding = 0px;
                            }
                        }
                    }
                }
            }
        }
    }
}