import { Pallet } from "./style.slint";
import { SimpleButton } from "buttons.slint";

export component NumberInput {
    width: 76px;
    height: 28px;

    in property <brush> background: Pallet.input-background;

    in property <length> border-width: 1px;
    in property <brush> border-color: Pallet.input-border;

    in property <length> image-size: 15px;

    in-out property <int> value: 1;
    in property <int> min: 0;
    in property <int> max: 100;

    in property <int> step: 1;


    Rectangle {
        width: parent.width;
        height: parent.height;

        background: parent.background;

        border-width: parent.border-width;
        border-color: parent.border-color;
        
        SimpleButton {
            background: Pallet.input-background;
            background-select: Pallet.input-background.brighter(0.5);

            border-radius: 0;
            height: parent.height - 2px;
            width: (parent.height < parent.width ? parent.height : parent.width) - 2px;
            x: 1px;

            Image {
                source: @image-url("../assets/icons/input_minus.png");
                image-rendering: pixelated;
                colorize: Pallet.input-border;
                x: self.width - 10px;
                y: self.height - 8px;
                width: image-size;
                height: image-size;
            }
        }

        Text {
            text: value;
            color: Pallet.input-text;
            font-family: "Roboto";
            font-size: 16px;
            font-weight: 500;
        }

        SimpleButton {
            background: Pallet.input-background;
            background-select: Pallet.input-background.brighter(0.5);

            border-radius: 0;
            height: parent.height - 2px;
            width: (parent.height < parent.width ? parent.height : parent.width) - 2px;
            x: parent.width - self.width - 1px;

            Image {
                source: @image-url("../assets/icons/input_plus.png");
                image-rendering: pixelated;
                colorize: Pallet.input-border;
                x: self.width - 7px;
                y: self.height - 8px;
                width: image-size;
                height: image-size;
            }
        }
    }
}

export component KeypadInput {
    
    width: 240px;
    height: 60px; 

    in property <string> value: "1234567890";

    Rectangle {
        background: Pallet.input-keypad-background;
        HorizontalLayout {
            padding-left: 8px;
            Text {
                text: value;
                color: Pallet.input-text;
                vertical-alignment: center;
                font-family: "Roboto";
                font-size: 24px;
                font-weight: 500;
            }

            SimpleButton {
                background: transparent;
                border-radius: 0;
                width: 42px;
                height: parent.height;

                Image {
                    source: @image-url("../assets/icons/X.png");
                    width: 20px;
                    height: 20px;
                }

                Rectangle {
                    background: Pallet.input-border;
                    border-radius: 0;
                    width: 1px;
                    height: parent.height - 16px;
                    x: -1px;
                }
            }
        }
    }
}