import { Pallet } from "style.slint";
import { Header } from "header.slint";

export component Page {
    width: 1280px;
    height: 800px;

    in property <brush> background: white;

    in property <string> title: "Page";
    
    
    GridLayout {
        // Header
        Header {
            col: 0;
        }
        // Main content of the page
        Rectangle {
            col: 1;
            background: root.background;
            @children
        }
    }
}