import { PageOne, PageOneLogic } from "../views/pages/PageOne.slint";
export { PageOne, PageOneLogic }

import { PageTwo, PageTwoLogic } from "../views/pages/PageTwo.slint";
export { PageTwo, PageTwoLogic }

import { HomePage, HomePageLogic } from "../views/pages/HomePage.slint";
export { HomePage, HomePageLogic }

import { SchindlerPage, SchindlerPageLogic } from "../views/pages/SchindlerPage.slint";
export { SchindlerPage, SchindlerPageLogic }