import { HomePage, HomePageLogic } from "../views/pages/HomePage.slint";
export { HomePage, HomePageLogic }

import { SchindlerPage, SchindlerPageLogic } from "../views/pages/SchindlerPage.slint";
export { SchindlerPage, SchindlerPageLogic }

import { StyleTestPage } from "../views/pages/StyleTestPage.slint";
export { StyleTestPage }

import { Header, HeaderLogic } from "header.slint";
export { Header, HeaderLogic }