import { Pallet } from "style.slint";
import { Header, HeaderLogic } from "header.slint";

export component Page {
    width: 1280px;
    height: 800px;

    in property <brush> background: white;

    in property <string> title: "Page";
    
    init => {
        HeaderLogic.maximized = false;
    }

    GridLayout {
        
        // Main content of the page
        Rectangle {
            col: 1;
            width: 1280px - 50px;
            background: root.background;
            @children
        }
        // Header
        Rectangle {
            width: 50px;
            col: 0;
            Header {
                title: root.title;
            }
        }
    }
}