import { OldButton } from "../../components/old.slint";

export component ModuSoftSchMenu inherits Rectangle {
    width: 1280px;
    height: 800px;

    background: #ffffff;

    callback schindler-page();

    callback back-to-menu-page();

    HorizontalLayout {
        spacing: 7px;
        x: root.width / 2 - 287px;
        y: root.height / 2 - self.height / 3.3;
        VerticalLayout {
            spacing: 7px;
            
            HorizontalLayout {
                spacing: 7px;
                OldButton {
                    width: 85px;
                    text: "?";
                    clicked => {
                    }
                }
                OldButton {
                    width: 500px;
                    text: "Modu-soft.sch.v1";
                    clicked => {
                    }
                }
            } 

            HorizontalLayout {
                spacing: 7px;
                OldButton {
                    width: 85px;
                    text: "?";
                    clicked => {
                    }
                }
                OldButton {
                    width: 500px;
                    text: "Modu-soft.sch.v2";
                    clicked => {
                    }
                }
            }

            HorizontalLayout {
                spacing: 7px;
                OldButton {
                    width: 85px;
                    text: "?";
                    clicked => {
                    }
                }
                OldButton {
                    width: 500px;
                    text: "Modu-soft.sch.v3";
                    clicked => {
                    }
                }
            }

            HorizontalLayout {
                spacing: 7px;
                OldButton {
                    width: 85px;
                    text: "?";
                    clicked => {
                    }
                }
                OldButton {
                    width: 500px;
                    text: "Modu-soft.sch.v5";
                    clicked => {
                    }
                }
            }

            HorizontalLayout {
                spacing: 7px;
                OldButton {
                    width: 85px;
                    text: "?";
                    clicked => {
                    }
                }
                OldButton {
                    width: 500px;
                    text: "Modu-soft.sch_3300";
                    clicked => {
                        schindler-page();
                    }
                }
            }
        }   
    }

    OldButton {
        width: 200px;
        height: 50px;
        x: root.width - 200px - 40px;
        y: root.height - 50px - 40px;

        text: "Back";
        font-size: 28px;
        font-weight: 400;

        clicked => {
            back-to-menu-page();
        }
    }
}
