import { OldButton } from "../../components/old.slint";

export component ModuSoftKnePage inherits Rectangle {
    width: 1280px;
    height: 800px;

    background: #ffffff;

    callback modusoft-kne();
    callback modusoft-ots();
    callback modusoft-thy();
    callback modusoft-ora();
    callback modusoft-sch();
    callback modu-test();
    callback back-to-menu-page();

    HorizontalLayout {
        spacing: 7px;
        x: root.width / 2 - 280px;
        y: root.height / 2 - self.height / 4;

        VerticalLayout {
            spacing: 7px;

            HorizontalLayout {
                spacing: 7px;
                
                OldButton {
                    text: "?";
                    width: 85px;
                }
                OldButton {
                    width: 500px;
                    text: "Modu-soft.kne.v1";
                    clicked => {
                        modusoft-kne();
                    }
                }
            }

            HorizontalLayout {
                spacing: 7px;
                
                OldButton {
                    text: "?";
                    width: 85px;
                }
                OldButton {
                    width: 500px;
                    text: "Modu-soft.kne.v2";
                    clicked => {
                        modusoft-kne();
                    }
                }
            }

            HorizontalLayout {
                spacing: 7px;
                
                OldButton {
                    text: "?";
                    width: 85px;
                }
                OldButton {
                    width: 500px;
                    text: "Modu-soft.kne.v3";
                    clicked => {
                        modusoft-kne();
                    }
                }
            }

            HorizontalLayout {
                spacing: 7px;
                
                OldButton {
                    text: "?";
                    width: 85px;
                }
                OldButton {
                    width: 500px;
                    text: "Modu-soft.kne.v4";
                    clicked => {
                        modusoft-kne();
                    }
                }
            }
        }

    }
    
    OldButton {
        width: 200px;
        height: 50px;
        x: root.width - 200px - 40px;
        y: root.height - 50px - 40px;

        text: "Back";
        font-size: 28px;
        font-weight: 400;

        clicked => {
            back-to-menu-page();
        }
    }
}
