import { Page } from "../../components/page.slint";
import { Pallet } from "../../components/style.slint";
import { SimpleButton } from "../../components/buttons.slint";

struct console-output {
    time : string,
    message : string
}

export global SchindlerPageLogic {
    // Every property and/or callback you want to 
    // expose to Rust must be declared here...
    callback keypad-clicked(keypad-value: string);

    in property <string> console-main: "";
    in property <string> console-time: "";
    in property <[console-output]> output-message : [
        {time: "00:00:00", message: "Hello World!"},
        {time: "00:00:00", message: "Hello World 2!"}
    ];
}

export component SchindlerPage inherits Page {
    title: "Schindler 3300";
    background: Pallet.background;
    GridLayout {
        spacing: 12px;
        padding: 12px;

        Rectangle {
            background: Pallet.panel-background;
            rowspan: 2;
            width: 296px;

            Text {
                text: "? ? ?";
            }
        }

        // Visual Info
        Rectangle {
            height: 514px;
            background: Pallet.panel-background;
            col: 1;
            row: 0;

            Text {
                text: "VISUAL INFO";
            }
        }

        // Console
        Rectangle {
            col: 1;
            row: 1;
            
            width: 600px;
            height: 250px;
            
            border-width: 1px;
            border-color: Pallet.console-border;
            background: Pallet.console-background;
            
            Flickable {
                interactive: true;
                width: parent.width;
                viewport-width: self.width;
                viewport-y: {
                    if (self.viewport-height > self.height) { self.height - self.viewport-height } 
                    else { 0px }   
                };

                VerticalLayout {
                    spacing: 4px;
                    padding-left: 5px;
                    padding-right: 5px;
                    padding-top: 5px;  
                    padding-bottom: 5px;
                    alignment: end;

                    for output-message[i] in SchindlerPageLogic.output-message : HorizontalLayout {
                        spacing: 6px;
                        Rectangle {
                            width: 43px;
                            Text {
                                y: 0px;
                                text: SchindlerPageLogic.output-message[i].time;
                                wrap: word-wrap;
                                color: Pallet.console-time-text;
                                horizontal-alignment: center;
                                vertical-alignment: bottom;
                            }
                        }
                        
                        Rectangle {
                            width: 3px;
                            height: 3px;
                            background: Pallet.console-time-text;
                            y: 7px;
                        }


                        Text {
                            text: SchindlerPageLogic.output-message[i].message;
                            width: parent.width - 47px - 6px;
                            color: Pallet.console-main-text;
                            horizontal-alignment: left;
                            vertical-alignment: bottom;
                        }
                    }
                }
            } 
        }
        
        // Keypad
        Rectangle {
            background: Pallet.panel-background;
            width: 296px;

            col: 2;
            row: 0;
            rowspan: 2;

            property <[[string]]> keypad-rows: [["1", "2", "3"], 
                                                ["4", "5", "6"], 
                                                ["7", "8", "9"], 
                                                ["<>", "0", "><"]];

            VerticalLayout {
                alignment: end;                
                padding: keypad-spacing;
                property <length> keypad-spacing: 8px;
                spacing: keypad-spacing;

                for keypad-row in keypad-rows : HorizontalLayout {
                    alignment: space-between;

                    for keypad-char in keypad-row : SimpleButton {
                        width: (parent.width / 3) - keypad-spacing;
                        height: (parent.width / 3) - keypad-spacing;
                        border-radius: 2px;
                        background: #1c1c1c;
                        background-select: #353844;
                        label: keypad-char;

                        keypad-text :=Text {
                            vertical-alignment: center;
                            horizontal-alignment: center;
                            font-size: 20px;
                            text: keypad-char;
                        }

                        clicked => {
                            SchindlerPageLogic.keypad-clicked(keypad-char);
                        }
                    }
                }
            }
        }
    }
}

