import { Page } from "../../components/page.slint";
import { Pallet } from "../../components/style.slint";


component ButtonRefference {
    // width: 50px;
    // height: 50px;

    in property <length> border-radius: 0px;
    in property <length> button-width: 50px;
    in property <length> button-height: 50px;

    GridLayout {
        button := Rectangle {
            row: 0;
            col: 0;
            background: #16a6ff;
            width: button-width;
            height: button-height;
            border-radius: root.border-radius;
        }
        Rectangle {
            row: 1;
            col: 0;
            Text {
                y: 0px;
    
                text: button.width / 1px + "px";
                color: #ffffff;
                font-size: 16px;
                font-weight: 600;
                horizontal-alignment: center;
                vertical-alignment: top;
            }

        }
        Rectangle {
            row: 0;
            col: 1;
            Text {
                x: 4px;
    
                text: button.height / 1px + "px";
                color: #ffffff;
                font-size: 16px;
                font-weight: 600;
                horizontal-alignment: center;
                vertical-alignment: top;
            }

        }

    }

}

export component StyleTestPage inherits Page {
    background: Pallet.background;

    GridLayout {
        padding: 24px;
        // FONTS
        Rectangle {
            width: 615px;
            height: 800px;

            HorizontalLayout {
                padding-right: 24px;
                alignment: space-between;
                VerticalLayout {  
                    height: 200px;
    
                    Text {
                        font-family: "Roboto";
                        font-size: 8px;
                        color: #ffffff;
                        text: "Font size: 8px";
                    }
                    Text {
                        font-family: "Roboto";
                        font-size: 10px;
                        color: #ffffff;
                        text: "Font size: 10px";
                    }
                    Text {
                        font-family: "Roboto";
                        font-size: 12px;
                        color: #ffffff;
                        text: "Font size: 12px";
                    }
                    Text {
                        font-family: "Roboto";
                        font-size: 14px;
                        color: #ffffff;
                        text: "Font size: 14px";
                    }
                    Text {
                        font-family: "Roboto";
                        font-size: 16px;
                        color: #ffffff;
                        text: "Font size: 16px";
                    }
                    Text {
                        font-family: "Roboto";
                        font-size: 18px;
                        color: #ffffff;
                        text: "Font size: 18px";
                    }
                    Text {
                        font-family: "Roboto";
                        font-size: 20px;
                        color: #ffffff;
                        text: "Font size: 20px";
                    }
                    Text {
                        font-family: "Roboto";
                        font-size: 22px;
                        color: #ffffff;
                        text: "Font size: 22px";
                    }
                    Text {
                        font-family: "Roboto";
                        font-size: 24px;
                        color: #ffffff;
                        text: "Font size: 24px";
                    }
                }
                VerticalLayout {  
                    height: 50px;
                    
                    Text {
                        font-family: "Roboto";
                        font-size: 18px;
                        color: #ffffff;
                        font-weight: 500;
                        text: "Font weight: < 500";
                    }

                    Text {
                        font-family: "Roboto";
                        font-size: 18px;
                        color: #ffffff;
                        font-weight: 600;
                        text: "Font weight: > 600";
                    }
                    
                }
                VerticalLayout {
                    height: 50px;
                    Text {
                        font-family: "Roboto";
                        font-size: 18px;
                        color: #ffffff;
                        text: "Normal:   #FFFFFF";
                    }
                    Text {
                        font-family: "Roboto";
                        font-size: 18px;
                        color: #707070;
                        text: "Disabled: #707070";
                    }
                }
            }
        }
        // BUTTONS
        Rectangle {
            HorizontalLayout {
                padding-left: 24px;
                padding-right: 36px;
                alignment: space-between;

                ButtonRefference {
                    button-width: 30px;
                    button-height: 30px;
                }

                ButtonRefference {
                    button-width: 40px;
                    button-height: 40px;
                }

                ButtonRefference {
                    button-width: 50px;
                    button-height: 50px;
                }

                ButtonRefference {
                    button-width: 70px;
                    button-height: 70px;
                }
            }
        }
    }
}