import { ColorScheme, Pallet, Fonts, font-style} from "./components/style.slint";

import { Header, HeaderLogic,
         HomePage, HomePageLogic,
         SchindlerPage, SchindlerPageLogic,
         StyleTestPage,
         SettingsPage, SettingsPageLogic
} from "./components/pages.slint";


// This is so Rust has access to global components
// Export every imported component you want to have access inside Rust
export { ColorScheme, Pallet, Fonts, font-style, HeaderLogic, SettingsPageLogic }
export { 
    HomePageLogic,
    SchindlerPageLogic
}


export enum Pages {
    Home,
    SchindlerPage,
    StyleTestPage,
    SettingsPage,
}


export component AppWindow inherits Window {
    // width: 1280px;
    // height: 800px;

    // full-screen: true;
    
    min-width: 1280px;
    min-height: 800px;

    in property <Pages> current-page: Pages.Home;

    if current-page == Pages.Home : HomePage {}
    if current-page == Pages.SchindlerPage : SchindlerPage {}
    if current-page == Pages.StyleTestPage : StyleTestPage {}
    if current-page == Pages.SettingsPage : SettingsPage {}
}